teamcity-agent:
  image: auras/teamcity-agent-android:latest
  environment:
    TEAMCITY_SERVER: http://teamcity-server:8111
  links:
  - teamcity-server:teamcity-server
teamcity-data:
  image: busybox
  volumes:
  - /var/lib/teamcity
  tty: true
  links:
  - postgres:postgres
postgres-data:
  image: busybox
  volumes:
  - /var/lib/postgresql/data/pgdata
  tty: true
teamcity-server:
  image: auras/teamcity-docker:2017.2.1
  links:
  - postgres:postgres
  volumes_from:
  - teamcity-data
  ports:
  - 8111:8111/tcp
postgres:
  image: postgres:latest
  environment:
    PGDATA: /var/lib/postgresql/data/pgdata
    POSTGRES_DB: teamcity
    POSTGRES_PASSWORD: teamcity
    POSTGRES_USER: teamcity
  stdin_open: true
  tty: true
  volumes_from:
  - postgres-data