server:
  image: auras/teamcity-docker
  ports:
    - 8111:8111
  volumes:
    - ./teamcity-storage:/var/lib/teamcity
agent:
  image: auras/teamcity-agent-android
  links:
    - server
  environment:
    TEAMCITY_SERVER: http://server:8111
